### ISSUE TITLE
Dancing Artisan 🕺 

### ISSUE THREAD

**Issue by tux19** [Snapmaker/Snapmaker-Artisan-Firmware-Issues#15]
Out of the blue after starting a print (from luban or on machine) the Artisan started making furious axis movements. Must be the Y-axis or Z-axis that work against each other. I hustled to the emergency stop button and neither could nor want to investigate that drama further. 

When it happens, there is terrible sound (like when the motor/belts move against an obstacle). The whole things starts to vibrate. 

It happened twice, both max 1-2 seconds. It is gone after a restart 🤷 

I know this repository is unfortunately not actively maintained. I post a public issue anyway maybe parachvte  or @tensile23  have already seen situations like this.

Best regards!

**Comment by parachvte** [comment]
Please contact support@snapmaker.com
