### ISSUE TITLE
Fan of controller is switching on and off in seconds

### ISSUE THREAD

**Issue by mmack** [Snapmaker/Snapmaker-Artisan-Firmware-Issues#5]
The fan off and on topic got way better since the last firmware update. However there still some really annoying part:

Just heat the whole bed manually to 80 degrees. Keep it there and at 79 degrees the fan goes on and at 80 it stops. So b/c it cools down to 79 in matter of seconds, it enables again.

So, on off in seconds...

**Comment by troian** [comment]
Those are PSUs fans (there are two 400W PSUs inside the controller). I’m surprised by selection of the PSU, as Artisan positioned as desktop system.

**Comment by scotthsl** [comment]
Hi all,
Thank you for your feedback, but I apologize that the software is currently unable to control the PSU's fan.
