### ISSUE TITLE
Bed levelling not working properly

### ISSUE THREAD

**Issue by ganymedes** [Snapmaker/Snapmaker-Artisan-Firmware-Issues#6]
On my Artisan the bed levelling is not working on large prints. Small prints are ok.

I heated the bed for 30min, did all the calibration and started the print. But every single time it nearly scratches the bed. When I adjust Z-Offset +0.2mm, it’s no longer scratching, but the print is still uneven! Please see video and picture below.

I also have reset the machine and started from scratch. Installed latest firmware, heated everything for 30min, did all the levelling again, same result.

Can you please try this on one of your machines?

Bed temperature: 70C
Nozzle Temp: 250C
Material: PETG
Firmware: 2.2.1
Luban Version: 4.7.1
Nozzle dimension: 0.6
Nozzle side: right

Regards

![image](https://user-images.githubusercontent.com/1248713/227723605-e4b1fe34-3dcd-43fe-b09d-711ef17d82cf.jpeg)

**Comment by KarstenSchwab** [comment]
Same problem like me with artisan . look at Bug Z offstet here in forum
https://github.com/Snapmaker/Snapmaker-Artisan-Firmware-Issues/issues/2
