### ISSUE TITLE
Air Purifier together connected with rotary module gives power failure

### ISSUE THREAD

**Issue by Bockhorn-IT** [Snapmaker/Snapmaker-Artisan-Firmware-Issues#8]
When connecting the air purifier together with the rotary module, the Artisan gives an error when powering on, that the air purifier has a power failure, so it's not possible to laser on 4th axis and clean the air during the operation.

**Comment by Bijan-A** [comment]
Are you sure about this? I just tested rotary with air purifier and it worked well. I have the latest firmware with rotary module plugged into Motion 1 port and the air purifier plugged into Addon 1.

**Comment by Bockhorn-IT** [comment]
You are right, with the actual firmware V2.2.4 it is not reproducible.
